"""Supabase table name constants.

Single source of truth - import from here instead of using string literals.
"""

USERS = "users"
EVENTS = "events"
EVENT_DATES = "event_dates"
EVENT_SUBMISSIONS = "event_submissions"
ORGANIZATIONS = "organizations"
ORGANIZATION_INTEGRATIONS = "organization_integrations"
ORGANIZATION_MEMBERS = "organization_members"
QR_CODES = "qr_codes"
QR_CODE_SCANS = "qr_code_scans"
POSTER_PAYOUTS = "poster_payouts"
POSTER_PAYOUT_REVIEWS = "poster_payout_reviews"
USER_GOING_EVENTS = "user_going_events"
V1_SAVED_EVENTS = "v1_saved_events"
USER_INTERACTIONS = "user_interactions"
USER_RECOMMENDATIONS = "user_recommendations"
USER_CREDITS = "user_credits"
CREDIT_TRANSACTIONS = "credit_transactions"
EVENT_PROMOTIONS = "event_promotions"
REPORTED_EVENTS = "reported_events"
WORKFLOW_RUNS = "workflow_runs"
NOTIFICATION_PREFERENCES = "notification_preferences"
NOTIFICATIONS_LOG = "notifications_log"
USER_SAVED_ORGANIZATIONS = "user_saved_organizations"
ORGANIZATION_INVITATIONS = "organization_invitations"
ORGANIZATION_MEMBERSHIPS = "organization_memberships"
SCHOOLS = "schools"
SITE_BANNER = "site_banner"
SCHOOL_EMAIL_DOMAINS = "school_email_domains"
VERIFICATION_TOKENS = "verification_tokens"
INSTAGRAM_PUBLISH_BATCHES = "instagram_publish_batches"
INSTAGRAM_PUBLISH_ITEMS = "instagram_publish_items"
INSTAGRAM_PUBLISHING_ACCOUNTS = "instagram_publishing_accounts"
POSITIONS = "positions"
