"""Supabase table name constants.

Single source of truth — import from here instead of using string literals.
"""

USERS = "users"
EVENTS = "events"
EVENT_DATES = "event_dates"
EVENTS_LISTING = "events_listing"
CLUBS = "clubs"
CLUB_INTEGRATIONS = "club_integrations"
QR_CODES = "qr_codes"
QR_CODE_SCANS = "qr_code_scans"
USER_SAVED_EVENTS = "user_saved_events"
USER_EVENT_RSVPS = "user_event_rsvps"
USER_INTERACTIONS = "user_interactions"
USER_RECOMMENDATIONS = "user_recommendations"
USER_CREDITS = "user_credits"
EVENT_SUBMISSIONS = "event_submissions"
EVENT_PROMOTIONS = "event_promotions"
REPORTED_EVENTS = "reported_events"
SCRAPED_EVENTS = "scraped_events"
SCRAPE_RUNS = "scrape_runs"
AB_TEST_EVENTS = "ab_test_events"
NOTIFICATION_PREFERENCES = "notification_preferences"
NOTIFICATIONS_LOG = "notifications_log"
