"""Interaction event constants and abuse-prevention bounds."""

DEFAULT_INTERACTION_LIMIT = 50
MAX_INTERACTION_BATCH_SIZE = 50
MAX_INTERACTION_METADATA_BYTES = 2048

MAX_DUPLICATE_INTERACTIONS = 3
DEDUP_WINDOW_MINUTES = 60
MAX_USER_INTERACTIONS_PER_WINDOW = 100

INTERACTION_CLICK = "click"
INTERACTION_DETAIL_VIEW = "detail_view"
INTERACTION_GOING = "going"
INTERACTION_UNGOING = "ungoing"
INTERACTION_SHARE = "share"

INTERACTION_TYPES = (
    INTERACTION_CLICK,
    INTERACTION_DETAIL_VIEW,
    INTERACTION_GOING,
    INTERACTION_UNGOING,
    INTERACTION_SHARE,
)
