"""Position validation limits."""

MAX_POSITION_TITLE_LENGTH = 200
MAX_POSITION_DESCRIPTION_LENGTH = 4000
MAX_POSITION_DETAIL_LENGTH = 1000
MAX_POSITION_REQUIREMENT_COUNT = 12
MAX_POSITION_REQUIREMENT_LENGTH = 300
MAX_POSITION_SOURCE_URL_LENGTH = 1024
