"""Rate limit and per-user cap constants."""

RATE_LIMIT_MAX_REQUESTS = 10
RATE_LIMIT_WINDOW_SECONDS = 60

AUTH_RATE_LIMIT_MAX_REQUESTS = 10
AUTH_RATE_LIMIT_WINDOW_SECONDS = 60
AUTH_SENSITIVE_RATE_LIMIT_MAX_REQUESTS = 5
AUTH_SENSITIVE_RATE_LIMIT_WINDOW_SECONDS = 60
AUTH_REFRESH_RATE_LIMIT_MAX_REQUESTS = 30
AUTH_REFRESH_RATE_LIMIT_WINDOW_SECONDS = 60

ANON_INTERACTION_RATE_LIMIT_MAX_REQUESTS = 60
ANON_INTERACTION_RATE_LIMIT_WINDOW_SECONDS = 60

QR_SCAN_RATE_LIMIT_MAX_REQUESTS = 30
QR_SCAN_RATE_LIMIT_WINDOW_SECONDS = 60

SUBMISSION_RATE_LIMIT_MAX_REQUESTS = 10
SUBMISSION_RATE_LIMIT_WINDOW_SECONDS = 3600
REPORT_RATE_LIMIT_MAX_REQUESTS = 5
REPORT_RATE_LIMIT_WINDOW_SECONDS = 60

MAX_SAVED_EVENTS_PER_USER = 10_000

CALENDAR_FEED_RATE_LIMIT_MAX_REQUESTS = 60
CALENDAR_FEED_RATE_LIMIT_WINDOW_SECONDS = 3600
