"""Scraping pipeline constants."""

from typing import Final

SCRAPING_HANDLES_PER_RUN = 100
SCRAPING_APIFY_TIMEOUT_SECONDS = 3600
SCRAPING_DEFAULT_CUTOFF_DAYS = 4
SCRAPING_SINGLE_USER_CUTOFF_DAYS = 1
SCRAPING_POLL_INTERVAL_SECONDS = 5

SCRAPING_SAME_CLUB_TITLE_THRESHOLD = 0.8
SCRAPING_TITLE_SIMILARITY_THRESHOLD = 0.7
SCRAPING_LOCATION_SIMILARITY_THRESHOLD = 0.5
SCRAPING_DESCRIPTION_SIMILARITY_THRESHOLD = 0.3

SCRAPE_RUN_RUNNING: Final = "running"
SCRAPE_RUN_SUCCESS: Final = "success"
SCRAPE_RUN_ERROR: Final = "error"
SCRAPE_RUN_NO_POSTS: Final = "no_posts"
SCRAPE_RUN_STATUSES = (
    SCRAPE_RUN_RUNNING,
    SCRAPE_RUN_SUCCESS,
    SCRAPE_RUN_ERROR,
    SCRAPE_RUN_NO_POSTS,
)
