"""Shared status constants for user-facing tables."""

from typing import Final

SUBMISSION_PENDING: Final = "pending"
SUBMISSION_APPROVED: Final = "approved"
SUBMISSION_REJECTED: Final = "rejected"
SUBMISSION_STATUSES = (SUBMISSION_PENDING, SUBMISSION_APPROVED, SUBMISSION_REJECTED)

REPORT_PENDING: Final = "pending"
REPORT_RESOLVED: Final = "resolved"
REPORT_DISMISSED: Final = "dismissed"
REPORT_STATUSES = (REPORT_PENDING, REPORT_RESOLVED, REPORT_DISMISSED)

EVENT_STATUS_ACTIVE: Final = "CONFIRMED"
EVENT_STATUS_CANCELLED: Final = "CANCELLED"
EVENT_STATUSES = (EVENT_STATUS_ACTIVE, EVENT_STATUS_CANCELLED)
