"""Shared status constants for user-facing tables."""

from typing import Final

REPORT_PENDING: Final = "pending"
REPORT_RESOLVED: Final = "resolved"
REPORT_DISMISSED: Final = "dismissed"
REPORT_STATUSES = (REPORT_PENDING, REPORT_RESOLVED, REPORT_DISMISSED)


SUBMISSION_PENDING: Final = "pending"
SUBMISSION_APPROVED: Final = "approved"
SUBMISSION_REJECTED: Final = "rejected"


INSTAGRAM_BATCH_GENERATING: Final = "generating"
INSTAGRAM_BATCH_READY_FOR_REVIEW: Final = "ready_for_review"
INSTAGRAM_BATCH_PUBLISHING: Final = "publishing"
INSTAGRAM_BATCH_PUBLISHED: Final = "published"
INSTAGRAM_BATCH_EMPTY: Final = "empty"
INSTAGRAM_BATCH_FAILED: Final = "failed"
INSTAGRAM_BATCH_STATUSES = (
    INSTAGRAM_BATCH_GENERATING,
    INSTAGRAM_BATCH_READY_FOR_REVIEW,
    INSTAGRAM_BATCH_PUBLISHING,
    INSTAGRAM_BATCH_PUBLISHED,
    INSTAGRAM_BATCH_EMPTY,
    INSTAGRAM_BATCH_FAILED,
)
