"""Shared validation limits for schemas and routers."""

MAX_SESSION_ID_LENGTH = 128
MAX_FULL_NAME_LENGTH = 255
MAX_FACULTY_LENGTH = 255
MAX_SCHOOL_LENGTH = 255
MAX_INTEREST_LENGTH = 100
MAX_INTERESTS_COUNT = 50
MAX_REPORT_REASON_LENGTH = 2000
MAX_REJECTION_REASON_LENGTH = 2000
MAX_AVATAR_URL_LENGTH = 2048
MAX_URL_LENGTH = 2048

MAX_SEARCH_QUERY_LENGTH = 200
MAX_STATUS_FILTER_LENGTH = 30

MAX_EVENT_TITLE_LENGTH = 300
MAX_EVENT_DESCRIPTION_LENGTH = 5000
MAX_EVENT_LOCATION_LENGTH = 500
MAX_EVENT_ORGANIZATION_LENGTH = 255
MAX_EVENT_SCHOOL_LENGTH = 255
MAX_EVENT_CATEGORY_LENGTH = 100
MAX_EVENT_HANDLE_LENGTH = 255
MAX_EVENT_FOOD_ITEM_LENGTH = 100
MAX_EVENT_FOOD_COUNT = 20

MAX_ORGANIZATION_NAME_LENGTH = 200
MAX_ORGANIZATION_TYPE_LENGTH = 100
MAX_ORGANIZATION_CATEGORY_LENGTH = 100
MAX_ORGANIZATION_CATEGORY_COUNT = 20
MAX_INTEGRATION_METADATA_KEYS = 20
MAX_INTEGRATION_METADATA_KEY_LENGTH = 64
MAX_INTEGRATION_METADATA_VALUE_LENGTH = 512
MAX_INTEGRATION_NAME_LENGTH = 200

MAX_EVENT_PRICE = 100_000
MAX_EVENT_DATA_BYTES = 32_000
MAX_USER_AGENT_LENGTH = 512
