-- Organization hiring positions displayed in the public positions directory.
--
-- One row is one advertised role. Instagram posts that advertise several
-- roles therefore share source metadata without collapsing the roles into a
-- JSON document that the API cannot filter or paginate independently.

BEGIN;

CREATE TABLE IF NOT EXISTS public.positions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id integer NOT NULL
        REFERENCES public.organizations(id) ON DELETE CASCADE,
    school_id integer NOT NULL
        REFERENCES public.schools(id) ON DELETE RESTRICT,
    title varchar(200) NOT NULL,
    description text NOT NULL,
    position_type varchar(32) NOT NULL,
    requirements jsonb NOT NULL DEFAULT '[]'::jsonb,
    commitment varchar(1000),
    compensation varchar(1000),
    location varchar(1000),
    application_url varchar(1024),
    contact_email varchar(320),
    deadline_date date,
    deadline_at timestamptz,
    source_url varchar(1024) NOT NULL,
    source_image_url varchar(1024),
    ingestion_source varchar(32) NOT NULL DEFAULT 'manual',
    is_active boolean NOT NULL DEFAULT true,
    added_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT positions_title_not_blank CHECK (length(btrim(title)) > 0),
    CONSTRAINT positions_description_not_blank CHECK (length(btrim(description)) > 0),
    CONSTRAINT positions_source_url_not_blank CHECK (length(btrim(source_url)) > 0),
    CONSTRAINT positions_requirements_array CHECK (jsonb_typeof(requirements) = 'array'),
    CONSTRAINT positions_type_valid CHECK (
        position_type IN (
            'executive',
            'committee',
            'volunteer',
            'staff',
            'internship',
            'general'
        )
    ),
    CONSTRAINT positions_ingestion_source_valid CHECK (
        ingestion_source IN ('manual', 'instagram_scraper', 'seed')
    ),
    CONSTRAINT positions_deadline_time_requires_date CHECK (
        deadline_at IS NULL OR deadline_date IS NOT NULL
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS positions_source_title_key
    ON public.positions (source_url, lower(title));
CREATE INDEX IF NOT EXISTS positions_school_open_deadline_idx
    ON public.positions (school_id, is_active, deadline_date, deadline_at, id);
CREATE INDEX IF NOT EXISTS positions_organization_idx
    ON public.positions (organization_id, id);
CREATE INDEX IF NOT EXISTS positions_type_idx
    ON public.positions (position_type);

CREATE OR REPLACE FUNCTION public.enforce_position_organization_school()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
    v_organization_school_id integer;
BEGIN
    SELECT organization.school_id
      INTO v_organization_school_id
      FROM public.organizations AS organization
     WHERE organization.id = NEW.organization_id;

    IF v_organization_school_id IS NULL
       OR NEW.school_id <> v_organization_school_id
    THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            MESSAGE = 'position school must match its organization school';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS enforce_position_organization_school ON public.positions;
CREATE TRIGGER enforce_position_organization_school
BEFORE INSERT OR UPDATE OF organization_id, school_id ON public.positions
FOR EACH ROW
EXECUTE FUNCTION public.enforce_position_organization_school();

ALTER TABLE public.positions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.positions FROM PUBLIC;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        EXECUTE 'REVOKE ALL ON public.positions FROM anon';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        EXECUTE 'REVOKE ALL ON public.positions FROM authenticated';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
        EXECUTE 'GRANT ALL ON public.positions TO service_role';
        EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public.positions_id_seq TO service_role';
    END IF;
END $$;

COMMIT;
