import type { SupportedLanguage } from "@/shared/constants/languages";

type LazyLanguage = Exclude<SupportedLanguage, "en">;
type TranslationModule = { default: Record<string, unknown> };
type TranslationLoader = () => Promise<TranslationModule>;

const LANGUAGE_LOADERS: Record<LazyLanguage, readonly TranslationLoader[]> = {
  "zh": [
    () => import("@/shared/locales/zh.json"),
    () => import("@/features/auth/locales/zh.json"),
    () => import("@/features/events/locales/zh.json"),
    () => import("@/features/clubs/locales/zh.json"),
    () => import("@/features/club-panel/locales/zh.json"),
    () => import("@/features/admin/locales/zh.json"),
    () => import("@/features/credits/locales/zh.json"),
    () => import("@/features/qrcode/locales/zh.json"),
    () => import("@/features/settings/locales/zh.json"),
    () => import("@/features/onboarding-demo/locales/zh.json"),
    () => import("@/features/posters/locales/zh.json"),
    () => import("@/features/positions/locales/zh.json"),
  ],
  "fr": [
    () => import("@/shared/locales/fr.json"),
    () => import("@/features/auth/locales/fr.json"),
    () => import("@/features/events/locales/fr.json"),
    () => import("@/features/clubs/locales/fr.json"),
    () => import("@/features/club-panel/locales/fr.json"),
    () => import("@/features/admin/locales/fr.json"),
    () => import("@/features/credits/locales/fr.json"),
    () => import("@/features/qrcode/locales/fr.json"),
    () => import("@/features/settings/locales/fr.json"),
    () => import("@/features/onboarding-demo/locales/fr.json"),
    () => import("@/features/posters/locales/fr.json"),
    () => import("@/features/positions/locales/fr.json"),
  ],
  "es": [
    () => import("@/shared/locales/es.json"),
    () => import("@/features/auth/locales/es.json"),
    () => import("@/features/events/locales/es.json"),
    () => import("@/features/clubs/locales/es.json"),
    () => import("@/features/club-panel/locales/es.json"),
    () => import("@/features/admin/locales/es.json"),
    () => import("@/features/credits/locales/es.json"),
    () => import("@/features/qrcode/locales/es.json"),
    () => import("@/features/settings/locales/es.json"),
    () => import("@/features/onboarding-demo/locales/es.json"),
    () => import("@/features/posters/locales/es.json"),
    () => import("@/features/positions/locales/es.json"),
  ],
  "pa-Guru": [
    () => import("@/shared/locales/pa-Guru.json"),
    () => import("@/features/auth/locales/pa-Guru.json"),
    () => import("@/features/events/locales/pa-Guru.json"),
    () => import("@/features/clubs/locales/pa-Guru.json"),
    () => import("@/features/club-panel/locales/pa-Guru.json"),
    () => import("@/features/admin/locales/pa-Guru.json"),
    () => import("@/features/credits/locales/pa-Guru.json"),
    () => import("@/features/qrcode/locales/pa-Guru.json"),
    () => import("@/features/settings/locales/pa-Guru.json"),
    () => import("@/features/onboarding-demo/locales/pa-Guru.json"),
    () => import("@/features/posters/locales/pa-Guru.json"),
    () => import("@/features/positions/locales/pa-Guru.json"),
  ],
  "ar": [
    () => import("@/shared/locales/ar.json"),
    () => import("@/features/auth/locales/ar.json"),
    () => import("@/features/events/locales/ar.json"),
    () => import("@/features/clubs/locales/ar.json"),
    () => import("@/features/club-panel/locales/ar.json"),
    () => import("@/features/admin/locales/ar.json"),
    () => import("@/features/credits/locales/ar.json"),
    () => import("@/features/qrcode/locales/ar.json"),
    () => import("@/features/settings/locales/ar.json"),
    () => import("@/features/onboarding-demo/locales/ar.json"),
    () => import("@/features/posters/locales/ar.json"),
    () => import("@/features/positions/locales/ar.json"),
  ],
  "hi": [
    () => import("@/shared/locales/hi.json"),
    () => import("@/features/auth/locales/hi.json"),
    () => import("@/features/events/locales/hi.json"),
    () => import("@/features/clubs/locales/hi.json"),
    () => import("@/features/club-panel/locales/hi.json"),
    () => import("@/features/admin/locales/hi.json"),
    () => import("@/features/credits/locales/hi.json"),
    () => import("@/features/qrcode/locales/hi.json"),
    () => import("@/features/settings/locales/hi.json"),
    () => import("@/features/onboarding-demo/locales/hi.json"),
    () => import("@/features/posters/locales/hi.json"),
    () => import("@/features/positions/locales/hi.json"),
  ],
  "fil": [
    () => import("@/shared/locales/fil.json"),
    () => import("@/features/auth/locales/fil.json"),
    () => import("@/features/events/locales/fil.json"),
    () => import("@/features/clubs/locales/fil.json"),
    () => import("@/features/club-panel/locales/fil.json"),
    () => import("@/features/admin/locales/fil.json"),
    () => import("@/features/credits/locales/fil.json"),
    () => import("@/features/qrcode/locales/fil.json"),
    () => import("@/features/settings/locales/fil.json"),
    () => import("@/features/onboarding-demo/locales/fil.json"),
    () => import("@/features/posters/locales/fil.json"),
    () => import("@/features/positions/locales/fil.json"),
  ],
  "yue-Hant": [
    () => import("@/shared/locales/yue-Hant.json"),
    () => import("@/features/auth/locales/yue-Hant.json"),
    () => import("@/features/events/locales/yue-Hant.json"),
    () => import("@/features/clubs/locales/yue-Hant.json"),
    () => import("@/features/club-panel/locales/yue-Hant.json"),
    () => import("@/features/admin/locales/yue-Hant.json"),
    () => import("@/features/credits/locales/yue-Hant.json"),
    () => import("@/features/qrcode/locales/yue-Hant.json"),
    () => import("@/features/settings/locales/yue-Hant.json"),
    () => import("@/features/onboarding-demo/locales/yue-Hant.json"),
    () => import("@/features/posters/locales/yue-Hant.json"),
    () => import("@/features/positions/locales/yue-Hant.json"),
  ],
  "it": [
    () => import("@/shared/locales/it.json"),
    () => import("@/features/auth/locales/it.json"),
    () => import("@/features/events/locales/it.json"),
    () => import("@/features/clubs/locales/it.json"),
    () => import("@/features/club-panel/locales/it.json"),
    () => import("@/features/admin/locales/it.json"),
    () => import("@/features/credits/locales/it.json"),
    () => import("@/features/qrcode/locales/it.json"),
    () => import("@/features/settings/locales/it.json"),
    () => import("@/features/onboarding-demo/locales/it.json"),
    () => import("@/features/posters/locales/it.json"),
    () => import("@/features/positions/locales/it.json"),
  ],
  "de": [
    () => import("@/shared/locales/de.json"),
    () => import("@/features/auth/locales/de.json"),
    () => import("@/features/events/locales/de.json"),
    () => import("@/features/clubs/locales/de.json"),
    () => import("@/features/club-panel/locales/de.json"),
    () => import("@/features/admin/locales/de.json"),
    () => import("@/features/credits/locales/de.json"),
    () => import("@/features/qrcode/locales/de.json"),
    () => import("@/features/settings/locales/de.json"),
    () => import("@/features/onboarding-demo/locales/de.json"),
    () => import("@/features/posters/locales/de.json"),
    () => import("@/features/positions/locales/de.json"),
  ],
  "ur": [
    () => import("@/shared/locales/ur.json"),
    () => import("@/features/auth/locales/ur.json"),
    () => import("@/features/events/locales/ur.json"),
    () => import("@/features/clubs/locales/ur.json"),
    () => import("@/features/club-panel/locales/ur.json"),
    () => import("@/features/admin/locales/ur.json"),
    () => import("@/features/credits/locales/ur.json"),
    () => import("@/features/qrcode/locales/ur.json"),
    () => import("@/features/settings/locales/ur.json"),
    () => import("@/features/onboarding-demo/locales/ur.json"),
    () => import("@/features/posters/locales/ur.json"),
    () => import("@/features/positions/locales/ur.json"),
  ],
  "pt": [
    () => import("@/shared/locales/pt.json"),
    () => import("@/features/auth/locales/pt.json"),
    () => import("@/features/events/locales/pt.json"),
    () => import("@/features/clubs/locales/pt.json"),
    () => import("@/features/club-panel/locales/pt.json"),
    () => import("@/features/admin/locales/pt.json"),
    () => import("@/features/credits/locales/pt.json"),
    () => import("@/features/qrcode/locales/pt.json"),
    () => import("@/features/settings/locales/pt.json"),
    () => import("@/features/onboarding-demo/locales/pt.json"),
    () => import("@/features/posters/locales/pt.json"),
    () => import("@/features/positions/locales/pt.json"),
  ],
  "ru": [
    () => import("@/shared/locales/ru.json"),
    () => import("@/features/auth/locales/ru.json"),
    () => import("@/features/events/locales/ru.json"),
    () => import("@/features/clubs/locales/ru.json"),
    () => import("@/features/club-panel/locales/ru.json"),
    () => import("@/features/admin/locales/ru.json"),
    () => import("@/features/credits/locales/ru.json"),
    () => import("@/features/qrcode/locales/ru.json"),
    () => import("@/features/settings/locales/ru.json"),
    () => import("@/features/onboarding-demo/locales/ru.json"),
    () => import("@/features/posters/locales/ru.json"),
    () => import("@/features/positions/locales/ru.json"),
  ],
  "ta": [
    () => import("@/shared/locales/ta.json"),
    () => import("@/features/auth/locales/ta.json"),
    () => import("@/features/events/locales/ta.json"),
    () => import("@/features/clubs/locales/ta.json"),
    () => import("@/features/club-panel/locales/ta.json"),
    () => import("@/features/admin/locales/ta.json"),
    () => import("@/features/credits/locales/ta.json"),
    () => import("@/features/qrcode/locales/ta.json"),
    () => import("@/features/settings/locales/ta.json"),
    () => import("@/features/onboarding-demo/locales/ta.json"),
    () => import("@/features/posters/locales/ta.json"),
    () => import("@/features/positions/locales/ta.json"),
  ],
  "vi": [
    () => import("@/shared/locales/vi.json"),
    () => import("@/features/auth/locales/vi.json"),
    () => import("@/features/events/locales/vi.json"),
    () => import("@/features/clubs/locales/vi.json"),
    () => import("@/features/club-panel/locales/vi.json"),
    () => import("@/features/admin/locales/vi.json"),
    () => import("@/features/credits/locales/vi.json"),
    () => import("@/features/qrcode/locales/vi.json"),
    () => import("@/features/settings/locales/vi.json"),
    () => import("@/features/onboarding-demo/locales/vi.json"),
    () => import("@/features/posters/locales/vi.json"),
    () => import("@/features/positions/locales/vi.json"),
  ],
  "fa": [
    () => import("@/shared/locales/fa.json"),
    () => import("@/features/auth/locales/fa.json"),
    () => import("@/features/events/locales/fa.json"),
    () => import("@/features/clubs/locales/fa.json"),
    () => import("@/features/club-panel/locales/fa.json"),
    () => import("@/features/admin/locales/fa.json"),
    () => import("@/features/credits/locales/fa.json"),
    () => import("@/features/qrcode/locales/fa.json"),
    () => import("@/features/settings/locales/fa.json"),
    () => import("@/features/onboarding-demo/locales/fa.json"),
    () => import("@/features/posters/locales/fa.json"),
    () => import("@/features/positions/locales/fa.json"),
  ],
  "gu": [
    () => import("@/shared/locales/gu.json"),
    () => import("@/features/auth/locales/gu.json"),
    () => import("@/features/events/locales/gu.json"),
    () => import("@/features/clubs/locales/gu.json"),
    () => import("@/features/club-panel/locales/gu.json"),
    () => import("@/features/admin/locales/gu.json"),
    () => import("@/features/credits/locales/gu.json"),
    () => import("@/features/qrcode/locales/gu.json"),
    () => import("@/features/settings/locales/gu.json"),
    () => import("@/features/onboarding-demo/locales/gu.json"),
    () => import("@/features/posters/locales/gu.json"),
    () => import("@/features/positions/locales/gu.json"),
  ],
  "pl": [
    () => import("@/shared/locales/pl.json"),
    () => import("@/features/auth/locales/pl.json"),
    () => import("@/features/events/locales/pl.json"),
    () => import("@/features/clubs/locales/pl.json"),
    () => import("@/features/club-panel/locales/pl.json"),
    () => import("@/features/admin/locales/pl.json"),
    () => import("@/features/credits/locales/pl.json"),
    () => import("@/features/qrcode/locales/pl.json"),
    () => import("@/features/settings/locales/pl.json"),
    () => import("@/features/onboarding-demo/locales/pl.json"),
    () => import("@/features/posters/locales/pl.json"),
    () => import("@/features/positions/locales/pl.json"),
  ],
  "ko": [
    () => import("@/shared/locales/ko.json"),
    () => import("@/features/auth/locales/ko.json"),
    () => import("@/features/events/locales/ko.json"),
    () => import("@/features/clubs/locales/ko.json"),
    () => import("@/features/club-panel/locales/ko.json"),
    () => import("@/features/admin/locales/ko.json"),
    () => import("@/features/credits/locales/ko.json"),
    () => import("@/features/qrcode/locales/ko.json"),
    () => import("@/features/settings/locales/ko.json"),
    () => import("@/features/onboarding-demo/locales/ko.json"),
    () => import("@/features/posters/locales/ko.json"),
    () => import("@/features/positions/locales/ko.json"),
  ],
};

export async function loadLazyLanguage(
  language: LazyLanguage,
): Promise<Record<string, unknown>> {
  const loaders = LANGUAGE_LOADERS[language];
  if (!loaders) {
    throw new Error(`No loader registered for locale "${language}"`);
  }
  const modules = await Promise.all(loaders.map((load) => load()));
  return Object.assign({}, ...modules.map((module) => module.default));
}
