"""add events clubs and user profile fields

Revision ID: 20d14ccc324f
Revises: c014bad36b49
Create Date: 2026-03-09 12:07:33.419217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20d14ccc324f'
down_revision: Union[str, None] = 'c014bad36b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_name', sa.String(length=500), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('club_page', sa.String(length=500), nullable=True),
    sa.Column('ig', sa.String(length=255), nullable=True),
    sa.Column('discord', sa.String(length=255), nullable=True),
    sa.Column('club_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('dtstart_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dtend_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('food', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registration', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_image_url', sa.String(length=1024), nullable=True),
    sa.Column('club_type', sa.String(length=100), nullable=True),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('ig_handle', sa.String(length=255), nullable=True),
    sa.Column('discord_handle', sa.String(length=255), nullable=True),
    sa.Column('x_handle', sa.String(length=255), nullable=True),
    sa.Column('tiktok_handle', sa.String(length=255), nullable=True),
    sa.Column('fb_handle', sa.String(length=255), nullable=True),
    sa.Column('other_handle', sa.String(length=255), nullable=True),
    sa.Column('display_handle', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('faculty', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('school', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('is_first_year', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_first_year')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'school')
    op.drop_column('users', 'faculty')
    op.drop_table('events')
    op.drop_table('clubs')
    # ### end Alembic commands ###
