"""add logo_url to clubs

Revision ID: be3c90f6a8e8
Revises: 20d14ccc324f
Create Date: 2026-03-09 20:07:56.161248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3c90f6a8e8'
down_revision: Union[str, None] = '20d14ccc324f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('logo_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'logo_url')
    # ### end Alembic commands ###
