name: Temporary Dump Secrets

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Create dump file
        run: |
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> secrets_dump.env
          echo "ALLOWED_PARTIES=${{ secrets.ALLOWED_PARTIES }}" >> secrets_dump.env
          echo "APIFY_API_TOKEN=${{ secrets.APIFY_API_TOKEN }}" >> secrets_dump.env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> secrets_dump.env
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> secrets_dump.env
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> secrets_dump.env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> secrets_dump.env
          echo "CLERK_FRONTEND_API_KEY=${{ secrets.CLERK_FRONTEND_API_KEY }}" >> secrets_dump.env
          echo "CLERK_PEM_PUBLIC_KEY=${{ secrets.CLERK_PEM_PUBLIC_KEY }}" >> secrets_dump.env
          echo "CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}" >> secrets_dump.env
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> secrets_dump.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> secrets_dump.env
          echo "EMAIL_ENCRYPTION_KEY=${{ secrets.EMAIL_ENCRYPTION_KEY }}" >> secrets_dump.env
          echo "EMAIL_HASH_KEY=${{ secrets.EMAIL_HASH_KEY }}" >> secrets_dump.env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> secrets_dump.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> secrets_dump.env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> secrets_dump.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> secrets_dump.env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> secrets_dump.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> secrets_dump.env
          echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> secrets_dump.env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> secrets_dump.env
          echo "RESEND_FROM_EMAIL=${{ secrets.RESEND_FROM_EMAIL }}" >> secrets_dump.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> secrets_dump.env
          echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL }}" >> secrets_dump.env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> secrets_dump.env
          echo "SUPABASE_SECRET_KEY=${{ secrets.SUPABASE_SECRET_KEY }}" >> secrets_dump.env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> secrets_dump.env
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> secrets_dump.env

      - name: Upload secrets artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets-dump
          path: secrets_dump.env
          retention-days: 1
